### ISSUE TITLE
Controls & Screen Size

### ISSUE THREAD

**Issue by chrislloyd** [pda/roflbalt#1]
What's the recommended screen size and what are the controls?

PS. I'm in love you guys.

**Comment by pda** [comment]
Press any key to jump :)

You need at least that many columns and rows in your terminal/console:

``` ruby
SCREEN_WIDTH = 120
SCREEN_HEIGHT = 40
```

The actual screen size / resolution depends on your font size, spacing etc.

You can edit SCREEN_WIDTH, but increasing it too much will slow the game down.

SCREEN_HEIGHT is more fragile; we're yet to properly link the building heights etc to the screen height.

PS: awesome :)

**Comment by pda** [comment]
PPS: here's what it should look like: http://www.youtube.com/watch?v=VoHmJfXqwbM
