### ISSUE TITLE
terminal can't get commands after stopping game by ctrl+c

### ISSUE THREAD

**Issue by anklos** [pda/roflbalt#5]
Hi, 

In Mac terminal (lion), after using 'ctrl+c' to stop the game, terminal seems freeze. I need to open a new bash window to run commands.

**Comment by dhotson** [comment]
Yeah it's not resetting your terminal quite right. We're still working on that sorry.

You'll need to run the `reset` command (type it and hit enter.. even if you can't see the text).

**Comment by pda** [comment]
Probably the same issue as #2 …

I haven't had time to track down the escape codes to reset things properly. Doesn't help that I'm not affected by it, using zsh instead of bash :)

Workaround: run `reset` after exiting ROFLBALT.

**Comment by anklos** [comment]
wow quick response. Yes,  I just noticed that issue#2 talks the same problem. 'reset' works. Thanks
